// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDLilfX7jpiRE8naWIqAm23LLp0SpmZHAk',
    appId: '1:124874074089:web:2447b415f2325ee76d8d78',
    messagingSenderId: '124874074089',
    projectId: 'level-up-e4147',
    authDomain: 'level-up-e4147.firebaseapp.com',
    storageBucket: 'level-up-e4147.firebasestorage.app',
    measurementId: 'G-ERKJFLV6E4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBa0SkVH7AuP451STZF1PN0paYRyOcOdYA',
    appId: '1:124874074089:android:9f0e835237e5d45d6d8d78',
    messagingSenderId: '124874074089',
    projectId: 'level-up-e4147',
    storageBucket: 'level-up-e4147.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD3zNKebihgqcY7zjUEpAIP_KsUhDG6koE',
    appId: '1:124874074089:ios:1198c47172a87ebe6d8d78',
    messagingSenderId: '124874074089',
    projectId: 'level-up-e4147',
    storageBucket: 'level-up-e4147.firebasestorage.app',
    androidClientId: '124874074089-c13a3li6g0vhtvej6rte6t44ruc1pc85.apps.googleusercontent.com',
    iosClientId: '124874074089-ifp1hm3acira15ad2j96kvvtosiltvmv.apps.googleusercontent.com',
    iosBundleId: 'co.enspyr.levelUpCoach',
  );

}